=== mamiles/eManager/support/snmp4_13/uk/co/westhawk/test/test.dtd
<!-- /*
 * NAME
 *      $RCSfile: test.dtd,v $
 * DESCRIPTION
 *      [given below]
 * DELTA
 *      $Revision: 1.2 $
 *      $Author: birgit $
 * CREATED
 *      $Date: 2002/10/22 16:55:58 $
 * COPYRIGHT
 *      Westhawk Ltd
 * TO DO
 *
 */ -->

<!-- all tests -->
<!ELEMENT tests (test*)>

<!-- one test -->
<!ELEMENT test (version, host, port, socket_type, (community | usm), request*)>

<!-- test elements -->
<!ELEMENT version EMPTY>
  <!ATTLIST version no (1 | 2c | 3) "1">
<!ELEMENT host (#PCDATA)>
<!ELEMENT port (#PCDATA)>
<!ELEMENT socket_type EMPTY>
  <!ATTLIST socket_type type (STD | NET) "STD">

<!ELEMENT community (#PCDATA)>


<!-- usm elements -->
<!ELEMENT usm (username, context, auth, priv?)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT context (id, name)>
<!ELEMENT id (#PCDATA)> 
<!ELEMENT name (#PCDATA)> 

<!ELEMENT auth (aproto, apassw)?>
<!ATTLIST auth ado (yes | no) "no">

<!ELEMENT aproto (#PCDATA)>
<!ELEMENT apassw (#PCDATA)> 

<!ELEMENT priv (ppassw?)>
<!ATTLIST priv pdo (yes | no) "no">
<!ELEMENT ppassw (#PCDATA)>


<!-- request elements -->
<!ELEMENT request (oid*, non_rep?, max_rep?)>
  <!ATTLIST request 
            type (set | get | getNext | getBulk | mib | inform ) "getNext">

<!ELEMENT oid (comment?, variable, value?)>
<!ELEMENT variable (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT comment (#PCDATA)>

<!ELEMENT non_rep (#PCDATA)>
<!ELEMENT max_rep (#PCDATA)>

=== mamiles/eManager/support/snmp4_13/uk/co/westhawk/test/test.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE tests SYSTEM "./test.dtd">
<!--
-->
<tests>
    <test>
        <version no="1"/>
        <host>roke</host>
        <port>161</port>
        <socket_type type="STD"/>
        <community>public</community>
        <request type="getNext"> 
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
        </request>
        <request type="get"> 
            <oid>
                <comment>sysDescr</comment>
                <variable>1.3.6.1.2.1.1.1.0</variable>
            </oid>
        </request>
        <request type="set"> 
            <oid>
                <comment>sysLocation</comment>
                <variable>1.3.6.1.2.1.1.6.0</variable>
                <value>Westhawk Ltd</value>
            </oid>
        </request>
        <request type="mib"> 
            <oid>
                <comment>enterprises.42</comment>
                <variable>1.3.6.1.4.1.42</variable>
            </oid>
        </request>
    </test>
    <test>
        <version no="1"/>
        <host>ully</host>
        <port>161</port>
        <socket_type type="STD"/>
        <community>public</community>
        <request type="getNext"> 
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
        </request>
        <request type="get"> 
            <oid>
                <comment>sysDescr</comment>
                <variable>1.3.6.1.2.1.1.1.0</variable>
            </oid>
        </request>
        <request type="set"> 
            <oid>
                <comment>sysLocation</comment>
                <variable>1.3.6.1.2.1.1.6.0</variable>
                <value>Westhawk Ltd</value>
            </oid>
        </request>
    </test>
    <test>
        <version no="2c"/>
        <host>ully</host>
        <port>161</port>
        <socket_type type="STD"/>
        <community>public</community>
        <request type="getNext"> 
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
        </request>
        <request type="getBulk"> 
            <oid>
                <comment>sysUpTime</comment>
                <variable>1.3.6.1.2.1.1.3</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <non_rep>1</non_rep>
            <max_rep>5</max_rep>
        </request>
        <request type="get"> 
            <oid>
                <comment>sysDescr</comment>
                <variable>1.3.6.1.2.1.1.1.0</variable>
            </oid>
        </request>
        <request type="set"> 
            <oid>
                <comment>sysLocation</comment>
                <variable>1.3.6.1.2.1.1.6.0</variable>
                <value>Westhawk Ltd</value>
            </oid>
        </request>
        <request type="mib"> 
            <oid>
                <comment>host</comment>
                <variable>1.3.6.1.2.1.25</variable>
            </oid>
        </request>
    </test>
    <test>
        <version no="3"/>
        <host>212.30.73.70</host>
        <port>161</port>
        <socket_type type="STD"/>
        <usm>
            <username>noAuthUser</username>
            <context>
                <id>010000a1d41e4946</id>
                <name>public</name>
            </context>
            <auth ado="no"></auth>
        </usm>
        <request type="getNext"> 
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
        </request>
        <request type="getBulk"> 
            <oid>
                <comment>sysUpTime</comment>
                <variable>1.3.6.1.2.1.1.3</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <non_rep>1</non_rep>
            <max_rep>5</max_rep>
        </request>
        <request type="get"> 
            <oid>
                <comment>sysDescr</comment>
                <variable>1.3.6.1.2.1.1.1.0</variable>
            </oid>
        </request>
        <request type="set"> 
            <oid>
                <comment>sysLocation</comment>
                <variable>1.3.6.1.2.1.1.6.0</variable>
                <value>Westhawk Ltd</value>
            </oid>
        </request>
    </test>
    <test>
        <version no="3"/>
        <host>212.30.73.70</host>
        <port>161</port>
        <socket_type type="STD"/>
        <usm>
            <username>MD5_User</username>
            <context>
                <id>010000a1d41e4946</id>
                <name>public</name>
            </context>
            <auth ado="yes">
                <aproto>MD5</aproto>
                <apassw>AuthPassword</apassw>
            </auth>
            <priv pdo="no"></priv>
        </usm>
        <request type="getNext"> 
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
        </request>
        <request type="getBulk"> 
            <oid>
                <comment>sysUpTime</comment>
                <variable>1.3.6.1.2.1.1.3</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <non_rep>1</non_rep>
            <max_rep>5</max_rep>
        </request>
        <request type="get"> 
            <oid>
                <comment>sysDescr</comment>
                <variable>1.3.6.1.2.1.1.1.0</variable>
            </oid>
        </request>
        <request type="set"> 
            <oid>
                <comment>sysLocation</comment>
                <variable>1.3.6.1.2.1.1.6.0</variable>
                <value>Westhawk Ltd</value>
            </oid>
        </request>
    </test>
    <test>
        <version no="3"/>
        <host>212.30.73.70</host>
        <port>161</port>
        <socket_type type="STD"/>
        <usm>
            <username>MD5_DES_User</username>
            <context>
                <id>010000a1d41e4946</id>
                <name>public</name>
            </context>
            <auth ado="yes">
                <aproto>MD5</aproto>
                <apassw>AuthPassword</apassw>
            </auth>
            <priv pdo="yes">
                <ppassw>PrivPassword</ppassw>
            </priv>
        </usm>
        <request type="getNext"> 
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
        </request>
        <request type="getBulk"> 
            <oid>
                <comment>sysUpTime</comment>
                <variable>1.3.6.1.2.1.1.3</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <non_rep>1</non_rep>
            <max_rep>5</max_rep>
        </request>
        <request type="get"> 
            <oid>
                <comment>sysDescr</comment>
                <variable>1.3.6.1.2.1.1.1.0</variable>
            </oid>
        </request>
        <request type="set"> 
            <oid>
                <comment>sysLocation</comment>
                <variable>1.3.6.1.2.1.1.6.0</variable>
                <value>Westhawk Ltd</value>
            </oid>
        </request>
    </test>
    <test>
        <version no="3"/>
        <host>212.30.73.70</host>
        <port>161</port>
        <socket_type type="STD"/>
        <usm>
            <username>SHA_User</username>
            <context>
                <id>010000a1d41e4946</id>
                <name>public</name>
            </context>
            <auth ado="yes">
                <aproto>SHA1</aproto>
                <apassw>AuthPassword</apassw>
            </auth>
            <priv pdo="no"></priv>
        </usm>
        <request type="getNext"> 
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
        </request>
        <request type="getBulk"> 
            <oid>
                <comment>sysUpTime</comment>
                <variable>1.3.6.1.2.1.1.3</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <non_rep>1</non_rep>
            <max_rep>5</max_rep>
        </request>
        <request type="get"> 
            <oid>
                <comment>sysDescr</comment>
                <variable>1.3.6.1.2.1.1.1.0</variable>
            </oid>
        </request>
        <request type="set"> 
            <oid>
                <comment>sysLocation</comment>
                <variable>1.3.6.1.2.1.1.6.0</variable>
                <value>Westhawk Ltd</value>
            </oid>
        </request>
        <request type="mib"> 
            <oid>
                <comment>enterprises.412</comment>
                <variable>1.3.6.1.4.1.412</variable>
            </oid>
        </request>
    </test>
    <test>
        <version no="3"/>
        <host>212.30.73.70</host>
        <port>161</port>
        <socket_type type="STD"/>
        <usm>
            <username>SHA_DES_User</username>
            <context>
                <id>010000a1d41e4946</id>
                <name>public</name>
            </context>
            <auth ado="yes">
                <aproto>SHA1</aproto>
                <apassw>AuthPassword</apassw>
            </auth>
            <priv pdo="yes">
                <ppassw>PrivPassword</ppassw>
            </priv>
        </usm>
        <request type="getNext"> 
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
        </request>
