=== mamiles/eManager/support/snmp4_13/uk/co/westhawk/test/trap.dtd
<!-- /*
 * NAME
 *      $RCSfile: trap.dtd,v $
 * DESCRIPTION
 *      [given below]
 * DELTA
 *      $Revision: 1.1 $
 *      $Author: birgit $
 * CREATED
 *      $Date: 2001/03/07 12:11:44 $
 * COPYRIGHT
 *      Westhawk Ltd
 * TO DO
 *
 */ -->

<!-- all traps -->
<!ELEMENT traps (default, test*)>

<!-- default -->
<!ELEMENT default (port, socket_type)>

<!-- a trap test, listen for a certain host -->
<!ELEMENT test (version, host, port, socket_type, (community | usm))>

<!-- test elements -->
<!ELEMENT version EMPTY>
  <!ATTLIST version no (1 | 2c | 3) "1">
<!ELEMENT host (#PCDATA)>
<!ELEMENT port (#PCDATA)>
<!ELEMENT socket_type EMPTY>
  <!ATTLIST socket_type type (STD | NET) "STD">

<!ELEMENT community (#PCDATA)>


<!-- usm elements -->
<!ELEMENT usm (username, context, auth, priv?)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT context (id, name)>
<!ELEMENT id (#PCDATA)> 
<!ELEMENT name (#PCDATA)> 

<!ELEMENT auth (aproto, apassw)?>
<!ATTLIST auth ado (yes | no) "no">

<!ELEMENT aproto (#PCDATA)>
<!ELEMENT apassw (#PCDATA)> 

<!ELEMENT priv (ppassw?)>
<!ATTLIST priv pdo (yes | no) "no">
<!ELEMENT ppassw (#PCDATA)>

=== mamiles/eManager/support/snmp4_13/uk/co/westhawk/test/trap.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE traps SYSTEM "./trap.dtd">
<!--
-->
<traps>
    <default>
        <port>162</port>
        <socket_type type="STD"/>
    </default>
    <test>
        <version no="1"/>
        <host>roke</host>
        <port>161</port>
        <socket_type type="STD"/>
        <community>public</community>
    </test>
    <test>
        <version no="1"/>
        <host>selidor</host>
        <port>161</port>
        <socket_type type="STD"/>
        <community>public</community>
    </test>
    <test>
        <version no="2c"/>
        <host>selidor</host>
        <port>161</port>
        <socket_type type="STD"/>
        <community>public</community>
    </test>
    <test>
        <version no="1"/>
        <host>way</host>
        <port>161</port>
        <socket_type type="STD"/>
        <community>public</community>
    </test>
    <test>
        <version no="2c"/>
        <host>way</host>
        <port>161</port>
        <socket_type type="STD"/>
        <community>public</community>
    </test>
    <test>
        <version no="3"/>
        <host>way</host>
        <port>161</port>
        <socket_type type="STD"/>
        <usm>
            <username>noAuthUser</username>
            <context>
                <id></id>
                <name>public</name>
            </context>
            <auth ado="no"></auth>
        </usm>
    </test>
    <test>
        <version no="3"/>
        <host>way</host>
        <port>161</port>
        <socket_type type="STD"/>
        <usm>
            <username>authUser</username>
            <context>
                <id></id>
                <name>public</name>
            </context>
            <auth ado="yes">
                <aproto>MD5</aproto>
                <apassw>AuthPassword</apassw>
            </auth>
            <priv pdo="no"></priv>
        </usm>
    </test>
    <test>
        <version no="3"/>
        <host>way</host>
        <port>161</port>
        <socket_type type="STD"/>
        <usm>
            <username>privUser</username>
            <context>
                <id></id>
                <name>public</name>
            </context>
            <auth ado="yes">
                <aproto>MD5</aproto>
                <apassw>AuthPassword</apassw>
            </auth>
            <priv pdo="yes">
                <ppassw>PrivPassword</ppassw>
            </priv>
        </usm>
    </test>
    <test>
        <version no="3"/>
        <host>way</host>
        <port>161</port>
        <socket_type type="STD"/>
        <usm>
            <username>authSHAUser</username>
            <context>
                <id></id>
                <name>public</name>
            </context>
            <auth ado="yes">
                <aproto>SHA1</aproto>
                <apassw>AuthPassword</apassw>
            </auth>
            <priv pdo="no"></priv>
        </usm>
    </test>
    <test>
        <version no="3"/>
        <host>way</host>
        <port>161</port>
        <socket_type type="STD"/>
        <usm>
            <username>privSHAUser</username>
            <context>
                <id></id>
                <name>public</name>
            </context>
            <auth ado="yes">
                <aproto>SHA1</aproto>
                <apassw>AuthPassword</apassw>
            </auth>
            <priv pdo="yes">
                <ppassw>PrivPassword</ppassw>
            </priv>
        </usm>
    </test>
</traps>
