=== mamiles/eManager/schema/Applications.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Wm. Mark Stubbeman (Cisco Systems, Inc.) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="applications">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="appType" type="AppType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="AppInstance">
		<xs:sequence>
			<xs:element name="id" type="xs:string"/>
			<xs:element name="instrumentation" type="Instrumentation" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AppType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="rulebaseName" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="appInstance" type="AppInstance"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Instrumentation">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="method" type="Method" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Method">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="parameter" type="Parameter" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Parameter">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="description" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== mamiles/eManager/config/inventoryManager/Applications.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Wm. Mark Stubbeman (Cisco Systems, Inc.) -->
<!--Sample XML file generated by XML Spy v4.4 U (http://www.xmlspy.com)-->
<applications xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\schema\Applications.xsd">
	<appType>
		<name>HostResources</name>
		<rulebaseName>Linux2x</rulebaseName>
		<rulebaseName>Solaris2x</rulebaseName>
		<rulebaseName>Win2000</rulebaseName>
		<rulebaseName>WinXP</rulebaseName>
		<appInstance>
			<id>HostResources</id>
			<instrumentation>
				<name>COM.TIBCO.hawk.hma.EventLog</name>
				<method>
					<name>TBD</name>
					<description>TBD</description>
				</method>
			</instrumentation>
			<instrumentation>
				<name>COM.TIBCO.hawk.hma.FileStat</name>
				<method>
					<name>TBD</name>
					<description>TBD</description>
				</method>
			</instrumentation>
			<instrumentation>
				<name>COM.TIBCO.hawk.hma.FileSystem</name>
				<method>
					<name>TBD</name>
					<description>TBD</description>
				</method>
			</instrumentation>
			<instrumentation>
				<name>COM.TIBCO.hawk.hma.Network</name>
				<method>
					<name>TBD</name>
					<description>TBD</description>
				</method>
			</instrumentation>
			<instrumentation>
				<name>COM.TIBCO.hawk.hma.Performance</name>
				<method>
					<name>TBD</name>
					<description>TBD</description>
				</method>
			</instrumentation>
			<instrumentation>
				<name>COM.TIBCO.hawk.hma.Process</name>
				<method>
					<name>TBD</name>
					<description>TBD</description>
				</method>
			</instrumentation>
			<instrumentation>
				<name>COM.TIBCO.hawk.hma.Registry</name>
				<method>
					<name>TBD</name>
					<description>TBD</description>
				</method>
			</instrumentation>
			<instrumentation>
				<name>COM.TIBCO.hawk.hma.Services</name>
				<method>
					<name>TBD</name>
					<description>TBD</description>
				</method>
			</instrumentation>
			<instrumentation>
				<name>COM.TIBCO.hawk.hma.System</name>
				<method>
					<name>TBD</name>
					<description>TBD</description>
				</method>
			</instrumentation>
			<instrumentation>
				<name>COM.TIBCO.hawk.hma.TibRendezvous</name>
				<method>
					<name>TBD</name>
					<description>TBD</description>
				</method>
			</instrumentation>
			<instrumentation>
				<name>COM.TIBCO.hawk.microagent.Custom</name>
				<method>
					<name>TBD</name>
					<description>TBD</description>
				</method>
			</instrumentation>
			<instrumentation>
				<name>COM.TIBCO.hawk.microagent.Logfile</name>
				<method>
					<name>TBD</name>
					<description>TBD</description>
				</method>
			</instrumentation>
			<instrumentation>
				<name>COM.TIBCO.hawk.microagent.RuleBaseEngine</name>
				<method>
					<name>TBD</name>
					<description>TBD</description>
				</method>
			</instrumentation>
			<instrumentation>
				<name>COM.TIBCO.hawk.microagent.Self</name>
				<method>
					<name>TBD</name>
					<description>TBD</description>
				</method>
			</instrumentation>
			<instrumentation>
				<name>COM.TIBCO.hawk.microagent.SysInfo</name>
				<method>
					<name>TBD</name>
					<description>TBD</description>
				</method>
			</instrumentation>
		</appInstance>
	</appType>
</applications>
