=== mamiles/eManager/schema/Registration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Wm. Mark Stubbeman (Cisco Systems, Inc.) -->
<!--W3C Schema generated by XML Spy v4.4 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:complexType name="AppMgmtPolicies">
		<xs:sequence>
			<xs:element name="AppMgmtPolicy" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="LogDirectories">
		<xs:sequence>
			<xs:element name="LogDirectory" type="xs:string" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Logging">
		<xs:sequence>
			<xs:element name="LogDirectories" type="LogDirectories"/>
			<xs:element name="Transport" type="xs:string" minOccurs="0"/>
			<xs:element name="UserId" type="xs:string" minOccurs="0"/>
			<xs:element name="Password" type="xs:string" minOccurs="0"/>
			<xs:element name="UnixPrompt" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Registration">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="HostName" type="xs:string"/>
				<xs:element name="AppType" type="xs:string"/>
				<xs:element name="AppInstance" type="xs:string"/>
				<xs:element name="AppVersion" type="xs:string"/>
				<xs:element name="AppMgmtPolicies" type="AppMgmtPolicies"/>
				<xs:element name="ProcessPropertyFile" type="xs:string" minOccurs="0"/>
				<xs:element name="Logging" type="Logging"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== mamiles/eManager/config/inventoryManager/eManagerRegistration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XML Spy v4.4 U (http://www.xmlspy.com)-->
<Registration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\schema\Registration.xsd">
	<HostName>__HOST__</HostName>
	<AppType>eManager</AppType>
	<AppInstance>app</AppInstance>
	<AppVersion>__EMANAGER_VERSION__</AppVersion>
	<AppMgmtPolicies/>
	<Logging>
		<LogDirectories>
			<LogDirectory>__EMHOME__/logs</LogDirectory>
			<LogDirectory>__EMHOME__/tomcat/logs</LogDirectory>
			<LogDirectory>__EMHOME__/3rdparty/hawk/log</LogDirectory>
		</LogDirectories>
	</Logging>
</Registration>

=== mamiles/eManager/sdk/client/tibco/inventory/AppRegistration_MarcoTestAppInstance.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Wm. Mark Stubbeman (Cisco Systems, Inc.) -->
<!--Sample XML file generated by XML Spy v4.4 U (http://www.xmlspy.com)-->
<Registration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="S:\vws\root\wstubb-snap-emanager-main\emanager\schema\Registration.xsd">
	<HostName>wstubb-u60.cisco.com</HostName>
	<AppType>MarcoTestAppType</AppType>
	<AppInstance>MarcoTestAppInstance</AppInstance>
	<AppVersion>1.0.0</AppVersion>
	<AppMgmtPolicies>
		<AppMgmtPolicy>/vob/emanager/sdk/client/tibco/inventory/MarcoTest.hrb</AppMgmtPolicy>
	</AppMgmtPolicies>
	<Logging>
		<LogDirectories>
			<LogDirectory>String</LogDirectory>
		</LogDirectories>
	</Logging>
</Registration>

=== mamiles/eManager/sdk/client/tibco/process/TestAppRegistration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XML Spy v4.4 U (http://www.xmlspy.com)-->
<Registration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\schema\Registration.xsd">
	<HostName>sunfire-v880</HostName>
	<AppType>TestApp</AppType>
	<AppInstance>TestAppInst</AppInstance>
	<AppVersion>1.0.0</AppVersion>
	<AppMgmtPolicies/>
	<ProcessPropertyFile>/opt/CSCOemgmt/sdk/process/test_application/config/TestApp.processSequencer.properties</ProcessPropertyFile>
	<Logging>
		<LogDirectories>
			<LogDirectory>/opt/CSCOemgmt/sdk/process/test_application/bin</LogDirectory>
		</LogDirectories>
	</Logging>
</Registration>
